"""
Intelligent Heuristic Layer for Hardware Trojan Detection.

This module acts as an intelligent reasoning and scoring bridge between the
Graph Neural Network (GNN) and the Large Language Model (LLM).

Pipeline Role:
    GNN Probabilities + Graph Topology + Structural Evidence
                               ↓
                 extract_heuristic_features()
                               ↓
                 calculate_heuristic_score()
                               ↓
                 explain_heuristic_decision()
                               ↓
    Optimized Evidence & Structural Guidance for downstream LLM
"""

from __future__ import annotations

import math
from typing import Any, Dict, List, Tuple


DEFAULT_GNN_THRESHOLD = 0.95
DEFAULT_HEURISTIC_THRESHOLD = 0.60

# Baseline feature weights.
# These weights are normalized (sum to 1.0) and will be optimized
# using validation data in Phase 2 (src/optimizer.py).
DEFAULT_WEIGHTS: Dict[str, float] = {
    # GNN-derived features (0.45 total)
    "max_gnn_score": 0.15,
    "mean_gnn_score": 0.10,
    "high_confidence_ratio": 0.10,
    "confidence_margin": 0.10,

    # Graph structural features (0.55 total)
    "connectivity": 0.15,
    "sequential_ratio": 0.15,
    "exit_ratio": 0.10,
    "structural_density": 0.05,
    "po_proximity": 0.05,
    "trigger_concentration": 0.05,
}

from pathlib import Path
_ROOT = Path(__file__).resolve().parent.parent
OPTIMIZED_WEIGHTS_PATH = _ROOT / "results" / "heuristic" / "optimized_weights.json"


def load_optimized_weights(
    weights_path: Path | None = None,
) -> Tuple[Dict[str, float], float]:
    """
    Load learned weights and threshold from Phase 2 optimizer output.
    Falls back to DEFAULT_WEIGHTS and DEFAULT_HEURISTIC_THRESHOLD if file not found
    or if optimal_weights is invalid (empty, non-numeric, or zero-sum).
    """
    import json
    target_path = weights_path or OPTIMIZED_WEIGHTS_PATH
    if target_path.exists():
        try:
            with open(target_path, "r") as f:
                data = json.load(f)

            raw_weights = data.get("optimal_weights")
            weights = DEFAULT_WEIGHTS
            if isinstance(raw_weights, dict) and raw_weights:
                try:
                    converted = {str(k): float(v) for k, v in raw_weights.items()}
                    if sum(converted.values()) > 0.0:
                        weights = converted
                except (TypeError, ValueError):
                    weights = DEFAULT_WEIGHTS

            threshold = float(data.get("optimal_threshold", DEFAULT_HEURISTIC_THRESHOLD))
            return weights, threshold
        except Exception:
            pass
    return DEFAULT_WEIGHTS, DEFAULT_HEURISTIC_THRESHOLD


def _safe_float(val: Any, default: float = 0.0) -> float:
    try:
        return float(val)
    except (TypeError, ValueError):
        return default


def extract_heuristic_features(
    evidence: Dict[str, Any],
    gnn_threshold: float = DEFAULT_GNN_THRESHOLD,
) -> Dict[str, float]:
    """
    Extract comprehensive GNN-distribution and circuit-structural features
    from the structured evidence dictionary.

    Parameters:
    -----------
    evidence: Dict[str, Any]
        Structured evidence generated by src/evidence.py
    gnn_threshold: float
        Probability threshold above which a node is deemed high-confidence suspicious.

    Returns:
    --------
    Dict[str, float]: Dictionary of raw and normalized numerical features.
    """
    nodes: List[Dict[str, Any]] = evidence.get("nodes", [])
    if not nodes:
        raise ValueError("No nodes found in evidence dictionary.")

    # -------------------------------------------------------------
    # 1. GNN Prediction Distribution Features
    # -------------------------------------------------------------
    scores = [_safe_float(n.get("gnn_score"), 0.0) for n in nodes]
    scores_sorted = sorted(scores)
    n_nodes = len(scores)

    max_gnn_score = scores_sorted[-1]
    min_gnn_score = scores_sorted[0]
    mean_gnn_score = sum(scores) / n_nodes

    # Median score
    if n_nodes % 2 == 1:
        median_gnn_score = scores_sorted[n_nodes // 2]
    else:
        median_gnn_score = (scores_sorted[n_nodes // 2 - 1] + scores_sorted[n_nodes // 2]) / 2.0

    # Standard deviation (measures dispersion of suspiciousness across the region)
    variance = sum((s - mean_gnn_score) ** 2 for s in scores) / n_nodes
    std_gnn_score = math.sqrt(variance)

    # Interquartile range (IQR)
    q25 = scores_sorted[int(0.25 * n_nodes)]
    q75 = scores_sorted[int(0.75 * n_nodes)]
    score_iqr = q75 - q25

    # High-confidence node counts and ratio
    high_conf_scores = [s for s in scores if s >= gnn_threshold]
    high_conf_count = len(high_conf_scores)
    high_confidence_ratio = high_conf_count / n_nodes if n_nodes > 0 else 0.0

    # Confidence margin: difference between max suspiciousness and background mean
    # High margin indicates a localized anomalous cluster rather than diffuse noise
    low_conf_scores = [s for s in scores if s < gnn_threshold]
    bg_mean = (sum(low_conf_scores) / len(low_conf_scores)) if low_conf_scores else 0.0
    confidence_margin = max(0.0, max_gnn_score - bg_mean)

    # -------------------------------------------------------------
    # 2. Graph Structural Features
    # -------------------------------------------------------------
    region_info = evidence.get("region", {})
    structural_info = evidence.get("structural_evidence", {})

    internal_edges = float(region_info.get("internal_edges", 0))
    boundary_edges = float(region_info.get("boundary_edges", 0))
    total_region_edges = internal_edges + boundary_edges

    # Connectivity: ratio of internal interconnect to total boundary crossings
    # Trojans tend to form tightly coupled subcircuits (high internal connectivity)
    connectivity = (internal_edges / total_region_edges) if total_region_edges > 0 else 0.0

    # Structural density: internal edges relative to max possible directed edges
    possible_edges = n_nodes * (n_nodes - 1) if n_nodes > 1 else 1
    structural_density = min(1.0, internal_edges / possible_edges) if possible_edges > 0 else 0.0

    # Sequential gates (flip-flops, registers):
    # Hardware Trojans frequently use digital state machines or counters as triggers
    seq_list = structural_info.get("sequential_like_gates", [])
    sequential_count = float(len(seq_list))
    sequential_ratio = sequential_count / n_nodes if n_nodes > 0 else 0.0

    # Primary Inputs (PI) and Primary Outputs (PO) counts in the region
    pi_list = structural_info.get("primary_inputs", [])
    po_list = structural_info.get("primary_outputs", [])
    pi_count = float(len(pi_list))
    po_count = float(len(po_list))
    pi_ratio = pi_count / n_nodes if n_nodes > 0 else 0.0
    po_ratio = po_count / n_nodes if n_nodes > 0 else 0.0

    # Region exits:
    # A payload must reconnect to legitimate logic (external outputs) to alter functionality
    exits_list = structural_info.get("region_exits", region_info.get("exits", []))
    exit_count = float(len(exits_list))
    exit_ratio = exit_count / n_nodes if n_nodes > 0 else 0.0

    # Circuit position metrics (depth from PI, distance to PO)
    depths = [_safe_float(n.get("depth_from_input"), 0.0) for n in nodes]
    po_dists = [_safe_float(n.get("distance_to_output"), 0.0) for n in nodes]
    avg_depth = sum(depths) / n_nodes if n_nodes > 0 else 0.0
    avg_po_dist = sum(po_dists) / n_nodes if n_nodes > 0 else 0.0

    # PO proximity: inverse normalized PO distance (payloads are often within a few hops of POs)
    # Higher value = closer to primary outputs
    po_proximity = 1.0 / (1.0 + avg_po_dist)

    # Trigger concentration: ratio of high-confidence nodes to boundary exits
    # High ratio indicates concentrated trigger logic driving a stealthy single-point payload
    trigger_concentration = (high_conf_count / max(1.0, exit_count))
    # Normalize to [0, 1] using saturation function x / (1 + x)
    normalized_trigger_concentration = trigger_concentration / (1.0 + trigger_concentration)

    return {
        # GNN-derived
        "max_gnn_score": max_gnn_score,
        "mean_gnn_score": mean_gnn_score,
        "median_gnn_score": median_gnn_score,
        "std_gnn_score": std_gnn_score,
        "score_iqr": score_iqr,
        "high_confidence_count": float(high_conf_count),
        "high_confidence_ratio": high_confidence_ratio,
        "confidence_margin": confidence_margin,

        # Graph-derived
        "region_size": float(n_nodes),
        "internal_edges": internal_edges,
        "boundary_edges": boundary_edges,
        "connectivity": connectivity,
        "structural_density": structural_density,
        "sequential_count": sequential_count,
        "sequential_ratio": sequential_ratio,
        "pi_count": pi_count,
        "po_count": po_count,
        "pi_ratio": pi_ratio,
        "po_ratio": po_ratio,
        "exit_count": exit_count,
        "exit_ratio": exit_ratio,
        "avg_depth": avg_depth,
        "avg_po_dist": avg_po_dist,
        "po_proximity": po_proximity,
        "trigger_concentration": normalized_trigger_concentration,
    }


def calculate_heuristic_score(
    features: Dict[str, float],
    weights: Dict[str, float] | None = None,
) -> float:
    """
    Calculate the composite heuristic suspiciousness score.

    Mathematical formulation:
        H(x) = sum_{i} w_i * F_i

    where:
        - F_i in [0, 1] are normalized GNN and structural features.
        - sum(w_i) = 1.0
        - H(x) in [0, 1] is the uncalibrated heuristic score.

    Note: An uncalibrated score is NOT a probability; it represents a
    structural suspiciousness index.
    """
    if weights is None:
        weights = DEFAULT_WEIGHTS

    total_weight = sum(weights.values())
    if total_weight <= 0.0:
        raise ValueError("Sum of heuristic weights must be positive.")

    score = 0.0
    for feature_name, weight in weights.items():
        val = features.get(feature_name, 0.0)
        # Ensure feature is bounded in [0, 1] for linear weighting
        bounded_val = max(0.0, min(1.0, float(val)))
        score += (weight / total_weight) * bounded_val

    return score


def classify_heuristic(
    score: float,
    threshold: float = DEFAULT_HEURISTIC_THRESHOLD,
    uncertainty_margin: float = 0.08,
) -> str:
    """
    Classify the heuristic score into a categorical detection decision.

    Parameters:
    -----------
    score: float
        Computed heuristic score in [0, 1]
    threshold: float
        Decision boundary separating normal from suspicious
    uncertainty_margin: float
        Margin around threshold classified as UNCERTAIN

    Returns:
    --------
    'SUSPICIOUS' | 'NORMAL' | 'UNCERTAIN'
    """
    lower_bound = threshold - uncertainty_margin
    upper_bound = threshold + uncertainty_margin

    if score >= upper_bound:
        return "SUSPICIOUS"
    elif score <= lower_bound:
        return "NORMAL"
    else:
        return "UNCERTAIN"


def explain_heuristic_decision(
    features: Dict[str, float],
    weights: Dict[str, float] | None = None,
    top_n: int = 5,
) -> List[Dict[str, Any]]:
    """
    Produce feature attributions explaining which factors contributed
    most significantly to the heuristic suspiciousness score.

    Attribution Formula:
        Contribution_i = (w_i / sum(w)) * Feature_i

    Returns:
    --------
    List of factor dictionaries sorted in descending order of contribution.
    """
    if weights is None:
        weights = DEFAULT_WEIGHTS

    total_weight = sum(weights.values())

    explanations: List[Dict[str, Any]] = []

    descriptions = {
        "max_gnn_score": "Peak GNN suspiciousness probability across individual gates",
        "mean_gnn_score": "Average GNN suspiciousness score across the entire extracted region",
        "high_confidence_ratio": "Proportion of gates in the region classified as highly suspicious",
        "confidence_margin": "Gap between peak suspiciousness and background circuit logic",
        "connectivity": "Ratio of internal interconnects relative to external boundary edges",
        "sequential_ratio": "Concentration of sequential elements (flip-flops/registers characteristic of triggers)",
        "exit_ratio": "Density of region exits connecting into normal logic (payload attachment points)",
        "structural_density": "Internal edge density reflecting localized logic clustering",
        "po_proximity": "Proximity of the suspicious region to primary circuit outputs",
        "trigger_concentration": "Ratio of suspicious trigger logic relative to outward payload exits",
    }

    for feature_name, weight in weights.items():
        val = features.get(feature_name, 0.0)
        bounded_val = max(0.0, min(1.0, float(val)))
        norm_weight = weight / total_weight
        contribution = norm_weight * bounded_val

        explanations.append({
            "feature": feature_name,
            "value": round(bounded_val, 4),
            "weight": round(norm_weight, 4),
            "contribution": round(contribution, 4),
            "description": descriptions.get(feature_name, feature_name),
        })

    # Sort by descending contribution
    explanations.sort(key=lambda x: x["contribution"], reverse=True)
    return explanations[:top_n]


def rank_suspicious_nodes(
    evidence: Dict[str, Any],
    top_k: int = 15,
) -> List[Dict[str, Any]]:
    """
    Rank suspicious nodes combining GNN score with structural prominence
    (fanin, fanout, sequential type, proximity to output).
    """
    nodes = evidence.get("nodes", [])
    ranked_nodes = []

    for n in nodes:
        gnn_score = _safe_float(n.get("gnn_score"), 0.0)
        gate_type = str(n.get("type") or "unknown")
        is_seq = any(tag in gate_type.lower() for tag in ["dff", "reg", "latch"])
        fanin = int(_safe_float(n.get("fanin"), 0.0))
        fanout = int(_safe_float(n.get("fanout"), 0.0))
        po_dist = _safe_float(n.get("distance_to_output"), 999.0)

        # Composite node-level priority score
        # Priority combines GNN score with sequential trigger and payload exit indicators
        node_priority = (
            0.60 * gnn_score
            + 0.20 * (1.0 if is_seq else 0.0)
            + 0.10 * min(1.0, fanout / 5.0)
            + 0.10 * (1.0 / (1.0 + po_dist))
        )

        ranked_nodes.append({
            "gate": n.get("gate"),
            "type": gate_type,
            "gnn_score": round(gnn_score, 4),
            "is_sequential": is_seq,
            "fanin": fanin,
            "fanout": fanout,
            "po_distance": round(po_dist, 2),
            "composite_priority": round(node_priority, 4),
        })

    ranked_nodes.sort(key=lambda item: item["composite_priority"], reverse=True)
    return ranked_nodes[:top_k]


def analyze_heuristic(
    evidence: Dict[str, Any],
    weights: Dict[str, float] | None = None,
    threshold: float | None = None,
    gnn_threshold: float = DEFAULT_GNN_THRESHOLD,
) -> Dict[str, Any]:
    """
    End-to-end heuristic analysis of a circuit region.

    Produces:
        - Feature vector
        - Composite score
        - Categorical decision
        - Factor attribution explanations
        - Ranked high-priority nodes
    """
    if weights is None:
        opt_weights, opt_threshold = load_optimized_weights()
        weights = opt_weights
        if threshold is None:
            threshold = opt_threshold
    elif threshold is None:
        threshold = DEFAULT_HEURISTIC_THRESHOLD

    features = extract_heuristic_features(evidence, gnn_threshold=gnn_threshold)
    score = calculate_heuristic_score(features, weights=weights)
    decision = classify_heuristic(score, threshold=threshold)
    top_factors = explain_heuristic_decision(features, weights=weights)
    ranked_nodes = rank_suspicious_nodes(evidence)

    return {
        "heuristic_score": round(score, 6),
        "decision": decision,
        "threshold": threshold,
        "features": features,
        "factor_attribution": top_factors,
        "top_suspicious_nodes": ranked_nodes,
        "summary": (
            f"Heuristic classified region as {decision} with score {score:.4f} "
            f"(threshold: {threshold:.2f}). Top driver: {top_factors[0]['feature']} "
            f"(contribution: {top_factors[0]['contribution']:.4f})."
        ),
    }